### ISSUE TITLE
Wrong Hex.pm GitHub link

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [alertlogic/rebar_raw_resource#7]
Hi, @nalundgaard.

I think Hex.pm should point to this repository, shouldn't it? I see you listed there and here (and version 0.10.0 there and here), so it would make sense. 

Related: https://github.com/basho/rebar_raw_resource/issues/7.

**Comment by nalundgaard** [comment]
Hi Paulo, I agree with you, but as far as I know, it already does and always has. See [link](https://github.com/alertlogic/rebar_raw_resource/blob/a2a67a89c7d3937bfe5753dc5e58019daddd65a7/src/rebar_raw_resource.app.src#L30):

```erlang
{links, [{"Github", "https://github.com/alertlogic/rebar_raw_resource"}]}
```

What I see on [Hex.pm](https://hex.pm/packages/rebar_raw_resource/0.10.0) does correctly link to us. Here's my screenshot (see link preview in the bottom of the image).

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/1851445/94826298-c9df5300-03cc-11eb-9ab9-e417eec7cc12.png">

**Comment by nalundgaard** [comment]
Hmm, I guess the image was weirdly truncated? Here is another attempt:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/1851445/94826569-0e6aee80-03cd-11eb-9594-c9c033a22eef.png">

**Comment by paulo-ferraz-oliveira** [comment]
Hm... something funky must've happened this morning, then. I wouldn't have opened the ticket otherwise. In any case, glad that's the case. Closing.
